version: '3'

includes:
  vim:
    taskfile: taskfiles/vim.yml
  fzf:
    taskfile: taskfiles/fzf.yml
  go_essentials:
    taskfile: taskfiles/go_essentials.yml
  rust_extras:
    taskfile: taskfiles/rust_extras.yml
  rust_essentials:
    taskfile: taskfiles/rust_essentials.yml
  rust_trial:
    taskfile: taskfiles/rust_trial.yml
  bashdb:
    taskfile: taskfiles/bashdb.yml
  compiled_essentials:
    taskfile: taskfiles/compiled_essentials.yml
  compiled_extras:
    taskfile: taskfiles/compiled_extras.yml

tasks:
  all:
    deps:
      - rust_essentials
      - rust_extras
